name: CI
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
    paths:
      - '**.py'
      - 'requirements.txt'
      - 'tests/**'

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run tests
        run: pytest tests/ --verbose --cov=.
